# Generated by Django 4.2.7 on 2025-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
