# Generated by Django 4.2.7 on 2025-08-30 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diet_plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_calorie_goal", models.IntegerField()),
                ("protein_goal_grams", models.FloatField()),
                ("carbs_goal_grams", models.FloatField()),
                ("fat_goal_grams", models.FloatField()),
                ("fiber_goal_grams", models.FloatField(default=25)),
                ("water_goal_ml", models.IntegerField(default=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodNutritionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vitamin_c_mg", models.FloatField(default=0)),
                ("vitamin_d_iu", models.FloatField(default=0)),
                ("vitamin_a_iu", models.FloatField(default=0)),
                ("vitamin_e_mg", models.FloatField(default=0)),
                ("vitamin_k_mcg", models.FloatField(default=0)),
                ("thiamine_mg", models.FloatField(default=0)),
                ("riboflavin_mg", models.FloatField(default=0)),
                ("niacin_mg", models.FloatField(default=0)),
                ("vitamin_b6_mg", models.FloatField(default=0)),
                ("folate_mcg", models.FloatField(default=0)),
                ("vitamin_b12_mcg", models.FloatField(default=0)),
                ("calcium_mg", models.FloatField(default=0)),
                ("iron_mg", models.FloatField(default=0)),
                ("magnesium_mg", models.FloatField(default=0)),
                ("phosphorus_mg", models.FloatField(default=0)),
                ("potassium_mg", models.FloatField(default=0)),
                ("sodium_mg", models.FloatField(default=0)),
                ("zinc_mg", models.FloatField(default=0)),
                ("omega3_g", models.FloatField(default=0)),
                ("cholesterol_mg", models.FloatField(default=0)),
                ("sugar_g", models.FloatField(default=0)),
                (
                    "food",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_profile",
                        to="diet_plans.food",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutritionTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_recorded", models.DateField()),
                ("calories_consumed", models.FloatField(default=0)),
                ("protein_consumed", models.FloatField(default=0)),
                ("carbs_consumed", models.FloatField(default=0)),
                ("fat_consumed", models.FloatField(default=0)),
                ("fiber_consumed", models.FloatField(default=0)),
                ("sugar_consumed", models.FloatField(default=0)),
                ("calorie_goal_percentage", models.FloatField(default=0)),
                ("protein_goal_percentage", models.FloatField(default=0)),
                ("carbs_goal_percentage", models.FloatField(default=0)),
                ("fat_goal_percentage", models.FloatField(default=0)),
                ("nutrition_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_recorded"],
                "unique_together": {("user", "date_recorded")},
            },
        ),
        migrations.CreateModel(
            name="MicronutrientTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nutrient",
                    models.CharField(
                        choices=[
                            ("vitamin_c", "Vitamin C"),
                            ("vitamin_d", "Vitamin D"),
                            ("calcium", "Calcium"),
                            ("iron", "Iron"),
                            ("magnesium", "Magnesium"),
                            ("potassium", "Potassium"),
                            ("zinc", "Zinc"),
                            ("folate", "Folate"),
                            ("vitamin_b12", "Vitamin B12"),
                        ],
                        max_length=20,
                    ),
                ),
                ("daily_target", models.FloatField()),
                ("unit", models.CharField(default="mg", max_length=10)),
                (
                    "nutrition_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="micronutrient_targets",
                        to="nutrition.nutritiongoal",
                    ),
                ),
            ],
            options={
                "unique_together": {("nutrition_goal", "nutrient")},
            },
        ),
    ]
