# Generated by Django 4.2.7 on 2025-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('readable_date', models.CharField(blank=True, max_length=100)),
                ('hijri_date', models.CharField(blank=True, max_length=20)),
                ('hijri_month_en', models.CharField(blank=True, max_length=20)),
                ('hijri_month_ar', models.CharField(blank=True, max_length=20)),
                ('hijri_year', models.CharField(blank=True, max_length=10)),
                ('fajr', models.TimeField()),
                ('sunrise', models.TimeField()),
                ('dhuhr', models.TimeField()),
                ('asr', models.TimeField()),
                ('sunset', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('imsak', models.TimeField(blank=True, null=True)),
                ('midnight', models.TimeField(blank=True, null=True)),
                ('city', models.CharField(default='Dhaka', max_length=100)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('calculation_method', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'city', 'country')},
            },
        ),
    ]
