# Generated by Django 4.2.7 on 2025-08-30 05:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Diet"),
                            ("ramadan", "Ramadan Diet"),
                            ("weight_loss", "Weight Loss"),
                            ("weight_gain", "Weight Gain"),
                            ("muscle_gain", "Muscle Gain"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("duration_days", models.IntegerField(default=30)),
                ("daily_calorie_target", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("grains", "Grains & Cereals"),
                            ("proteins", "Proteins"),
                            ("dairy", "Dairy"),
                            ("fruits", "Fruits"),
                            ("vegetables", "Vegetables"),
                            ("fats", "Fats & Oils"),
                            ("beverages", "Beverages"),
                            ("snacks", "Snacks"),
                        ],
                        max_length=20,
                    ),
                ),
                ("calories_per_100g", models.FloatField()),
                ("protein_per_100g", models.FloatField(default=0)),
                ("carbs_per_100g", models.FloatField(default=0)),
                ("fat_per_100g", models.FloatField(default=0)),
                ("fiber_per_100g", models.FloatField(default=0)),
                ("is_halal", models.BooleanField(default=True)),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                (
                    "common_allergens",
                    models.TextField(blank=True, help_text="Comma-separated allergens"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                            ("suhoor", "Suhoor"),
                            ("iftar", "Iftar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("total_calories", models.FloatField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="diet_plans.dietplan",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number", "meal_type"],
                "unique_together": {("diet_plan", "day_number", "meal_type")},
            },
        ),
        migrations.CreateModel(
            name="MealFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_grams", models.FloatField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diet_plans.food",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_foods",
                        to="diet_plans.meal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietPlanProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_day", models.IntegerField(default=1)),
                ("completed_days", models.IntegerField(default=0)),
                ("skipped_days", models.IntegerField(default=0)),
                ("total_resets", models.IntegerField(default=0)),
                ("last_reset_date", models.DateTimeField(blank=True, null=True)),
                (
                    "diet_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="diet_plans.dietplan",
                    ),
                ),
            ],
        ),
    ]
