# Generated by Django 4.2.7 on 2025-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatemeal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatemeal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='todolist',
            constraint=models.UniqueConstraint(fields=('user', 'date_of_meal', 'meal_time'), name='uniq_user_date_mealtime'),
        ),
    ]
