# Generated by Django 4.2.7 on 2025-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plans', '0002_alter_generatemeal_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatemeal',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatemeal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatemeal',
            name='ai_generated_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
