# Generated by Django 4.2.7 on 2025-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plans', '0003_generatemeal_error_message_generatemeal_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatemeal',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='generatemeal',
            name='status',
        ),
        migrations.AlterField(
            model_name='generatemeal',
            name='ai_generated_data',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
