# Generated by Django 4.2.7 on 2025-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plans', '0004_remove_generatemeal_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatemeal',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
