# Generated by Django 4.2.7 on 2025-09-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plans', '0005_generatemeal_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatemeal',
            name='is_running',
            field=models.BooleanField(default=True),
        ),
    ]
