# Generated by Django 4.2.7 on 2025-08-30 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("meal_reminder", "Meal Reminder"),
                            ("water_reminder", "Water Reminder"),
                            ("weight_log", "Weight Log Reminder"),
                            ("achievement", "Achievement Notification"),
                            ("plan_reset", "Plan Reset Alert"),
                            ("motivation", "Motivational Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_reminders", models.BooleanField(default=True)),
                ("water_reminders", models.BooleanField(default=True)),
                ("weight_log_reminders", models.BooleanField(default=True)),
                ("achievement_notifications", models.BooleanField(default=True)),
                ("motivational_messages", models.BooleanField(default=True)),
                ("breakfast_reminder_time", models.TimeField(default="08:00:00")),
                ("lunch_reminder_time", models.TimeField(default="13:00:00")),
                ("dinner_reminder_time", models.TimeField(default="19:00:00")),
                (
                    "water_reminder_interval",
                    models.IntegerField(
                        default=2, help_text="Hours between water reminders"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("sent_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notificationtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
